### ISSUE TITLE
`withDefaultTargetMachine` does the Wrong Thing for cross-compilers

### ISSUE THREAD

**Issue by dfoxfranke** [bscarlet/llvm-general#106]
`withDefaultTargetMachine` calls `getHostCPUName` and `getHostCPUFeatures`, which doesn't make sense if LLVM is configured to cross-compile by default. It should use an empty string for the CPU name and an empty set (or empty map after bug #105 is fixed) for the features.

Consider adding a `withNativeTargetMachine` which uses `getProcessTargetTriple`, `getHostCPUName`, and `getHostCPUFeatures`.

**Comment by bscarlet** [comment]
withDefaultTargetMachine is deprecated on the older branches, and is now removed on the new 3.5 branch and master.
