### ISSUE TITLE
add type annotations for references in the llvm-3.2 branch

### ISSUE THREAD

**Issue by tmcdonell** [bscarlet/llvm-general#108]
RE: https://github.com/bscarlet/llvm-general/commit/7842578c4fc24aed6534dd723fc655d5d0fa74c5

Can you please apply this change to the llvm-3.2 branch as well. I use [libNVVM](http://docs.nvidia.com/cuda/libnvvm-api) to generate GPU code from LLVM IR, but currently this still only accepts LLVM 3.2 syntax.

My stuff also generates CPU code, and is thus compatible with the latest versions of llvm-general as well. I'd like to keep compatibility on both sides.

**Comment by bscarlet** [comment]
According to
http://docs.nvidia.com/cuda/nvvm-ir-spec/
The current version of NVVM is based on llvm-3.4.

Thank you for your patience. I'll keep this experience in mind when deciding when to obsolete more versions.

**Comment by tmcdonell** [comment]
Ah, looks NVIDIA have _finally_ updated their tools. Good catch, and thanks for considering this.
