### ISSUE TITLE
Fails to build with GHC 7.10

### ISSUE THREAD

**Issue by spacekitteh** [bscarlet/llvm-general#125]
[68 of 91] Compiling LLVM.General.Internal.Constant ( src/LLVM/General/Internal/Constant.hs, dist/dist-sandbox-92b4aa2/build/LLVM/General/Internal/Constant.o )

src/LLVM/General/Internal/Constant.hs:160:18:
    No instance for (DecodeM
                       DecodeAST (t0 Word64) (Foreign.C.Types.CUInt, Ptr Word64))
      arising from a use of ‘decodeM’
    The type variable ‘t0’ is ambiguous
    Note: there is a potential instance available:
      instance (Monad m, DecodeM m h c, Storable c, MonadIO m) =>
               DecodeM m [h] (Foreign.C.Types.CUInt, Ptr c)
        -- Defined at src/LLVM/General/Internal/Coding.hs:75:10
    In a stmt of a 'do' block: words <- decodeM (n, wsp)
    In the expression:
      do { np <- alloca;
           wsp <- liftIO $ FFI.getConstantIntWords c np;
           n <- peek np;
           words <- decodeM (n, wsp);
           .... }
    In a case alternative:
        (FFI.ValueSubclassId (Foreign.C.Types.CUInt 11))
          -> do { np <- alloca;
                  wsp <- liftIO $ FFI.getConstantIntWords c np;
                  n <- peek np;
                  .... }

src/LLVM/General/Internal/Constant.hs:161:42:
    No instance for (Foldable t0) arising from a use of ‘foldr’
    The type variable ‘t0’ is ambiguous
    Relevant bindings include
      words :: t0 Word64
        (bound at src/LLVM/General/Internal/Constant.hs:160:9)
    Note: there are several potential instances:
      instance Foldable (Const m) -- Defined in ‘Control.Applicative’
      instance Foldable (Either a) -- Defined in ‘Data.Foldable’
      instance Foldable Data.Functor.Identity.Identity
        -- Defined in ‘Data.Functor.Identity’
      ...plus 22 others
    In the second argument of ‘A.C.Int’, namely
      ‘(foldr
          (\ b a -> (a `shiftL` 64) .|. fromIntegral (b :: Word64)) 0 words)’
    In the second argument of ‘($)’, namely
      ‘A.C.Int
         (A.typeBits t)
         (foldr
            (\ b a -> (a `shiftL` 64) .|. fromIntegral (b :: Word64)) 0 words)’
    In a stmt of a 'do' block:
      return
      $ A.C.Int
          (A.typeBits t)
          (foldr
             (\ b a -> (a `shiftL` 64) .|. fromIntegral (b :: Word64)) 0 words)
cabal: Error: some packages failed to install:
llvm-general-3.4.4.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by bscarlet** [comment]
Fixed.
