### ISSUE TITLE
Support zeroinitalizer

### ISSUE THREAD

**Issue by NCrashed** [bscarlet/llvm-general#133]
There is no special constant `zeroinitializer` in `LLVM.General.AST.Constant`, hence it takes up to 20 seconds to pretty print AST with huge arrays (initialized to zero elements) instead of milleseconds.

**Comment by bscarlet** [comment]
Constant has Null to cover that case - it's not limited to pointer types.

**Comment by NCrashed** [comment]
Thanks!

**Comment by bscarlet** [comment]
One trick to remember is to write what you want as LLVM assembly, read it in and print the AST.
