### ISSUE TITLE
Alignment should be a ParameterAttribute rather than a FunctionAttribute

### ISSUE THREAD

**Issue by tmcdonell** [bscarlet/llvm-general#134]
Going by the LLVM docs [here](http://llvm.org/docs/LangRef.html#parameter-attributes) and [here](http://llvm.org/docs/LangRef.html#function-attributes), it looks like maybe the `Alignment` attribute ([here](https://github.com/bscarlet/llvm-general/blob/master/llvm-general-pure/src/LLVM/General/AST/Attribute.hs#L30)) should be part of `ParameterAttribute` rather than `FunctionAttribute` ?

**Comment by bscarlet** [comment]
Yes. The doc you link to seems to be the first version that includes it. I must have inferred from the code, and wrongly.

**Comment by bscarlet** [comment]
Fixed on 3.3 and later branches.
