### ISSUE TITLE
sigsegv when using call

### ISSUE THREAD

**Issue by feuerbach** [bscarlet/llvm-general#135]
The following simple code, when compiled and executed, results in a segmentation fault.

llvm-3.5.0, llvm-general-3.5.0.0

``` haskell
module Main where

import LLVM.General.AST
import LLVM.General.AST.CallingConvention
import LLVM.General.AST.Linkage
import LLVM.General.AST.Visibility
import LLVM.General.AST.Type

import qualified LLVM.General.Module as G
import qualified LLVM.General.Context as G

import Control.Monad.IO.Class
import Control.Monad.Trans.Except
import Control.Monad.Trans.Cont
import Control.Monad.Trans.Reader
import Control.Exception

type M r = ReaderT G.Context (ContT r IO)

runM :: M r r -> IO r
runM a =
  G.withContext $ flip runContT return . runReaderT a

errorIO = throwIO . ErrorCall

astToModule :: Module -> M r G.Module
astToModule m = ReaderT $ \ctx -> ContT $ \k ->
  either errorIO return =<< runExceptT
    (G.withModuleFromAST ctx m k)

main =
  runM $ do
    m <- astToModule fullModule
    liftIO $ putStrLn =<< G.moduleLLVMAssembly m

fullModule :: Module
fullModule =
  Module "regexp" Nothing Nothing [fundef]

fundef :: Definition
fundef =
  GlobalDefinition $
    Function
      Private Default Fast [] VoidType (Name "fun") ([], False) []
      Nothing 0 Nothing funblocks

funblocks :: [BasicBlock]
funblocks = [ startblock ]

startblock :: BasicBlock
startblock = BasicBlock (Name "start") [Do $ call (Name "fun") []] (Do $ Ret Nothing [])

call
  :: Name -- ^ function
  -> [Operand]
  -> Instruction
call fn ops =
  Call False C []
    (Right $ LocalReference void fn)
    (map (\o -> (o, [])) ops)
    [] []
```

**Comment by feuerbach** [comment]
I realized my mistake: I should have used GlobalReference instead of LocalReference for the function.

Still, it'd be nice to replace segfault with a meaningful error.

**Comment by bscarlet** [comment]
I think the actual problem which caused the crash is that you're using the wrong type in your reference. It should be the type of the function pointer, not the return type. I'm using an LLVM build with asserts turned on, and it fails with a complaint that it makes no sense to use a void-typed value as an operand. Especially during development, I highly recommend using a build of LLVM with asserts.

On the one hand, of course I don't like unsafe code that crashes. On the other, to avoid crashes like this I'd basically have to re-implement a fair-sized piece of LLVM, and even that would protect only against crashes in LLVM itself but not in generated code. The first class of protection was built into the older Haskell LLVM bindings ("llvm" on hackage) at the type level, but apparently the authors have not had time to maintain that version.

**Comment by feuerbach** [comment]
I didn't know about the assert-enabled build. Thanks.
