### ISSUE TITLE
Attempting to parse a module with debug data errors

### ISSUE THREAD

**Issue by elegios** [bscarlet/llvm-general#136]
I've built a c file with clang and attached debug data. Attempting to load the generated .ll file crashes with "unhandled type kind TypeKind 14". As far as I can tell TypeKind 14 is Metadata, which is indeed unhandled in the decoding part of Type.hs in internal.

Might it be possible for someone with a bit more insight into the code to look into it? I'd like to be able to read the debug info, but lack the time to look into it more thoroughly at the moment.

**Comment by bscarlet** [comment]
Fix now available in llvm-3.3.13.4 and llvm-general-3.4.4.4 on hackage.
