### ISSUE TITLE
Usage of GHCRTS breaks HsColour

### ISSUE THREAD

**Issue by abbradar** [bscarlet/llvm-general#139]
I'm building this package for NixOS. NixOS generic Haskell package builder calls haddock with  `--hyperlink-source` to get links to source code from documentation. HsColour is not built with `-rtsopts` by default and so it fails on your package -- this should also be so on non-NixOS (on Hackage, for example). We could suppress adding hyperlinked source to your package, but is there still need for those `GHCRTS` flags to be present? I tried to remove them and had successfully compiled both `llvm-general` and `llvm-general-pure` with HsColour.

**Comment by bscarlet** [comment]
Is there a particular reason you don't build hscolour with -rtsopts?

I'm reluctant to disable that setting without knowing specifically what fixed the problem.

**Comment by abbradar** [comment]
Not really, I think -- just keeping default flags. We would need to rebuild all Haskell packages if we change the flag though, I think (due to nature of Nix which forces rebuild of all reverse dependencies). For the sake of curiosity, what was the reason you've added GHCRTS?

**Comment by bscarlet** [comment]
At the time I added it, haddock ran out of stack and crashed without it. Looking back through the ghc docs, it looks like the default stack space was only 8M in the 7.4.x series, but since 7.6.x it's been much bigger. That's enough versions ago that it's acceptable for me to remove the setting now.

**Comment by abbradar** [comment]
Oh, very good! We can skip rebuilding everything or patching package on our side then.

**Comment by bscarlet** [comment]
Updated on llvm-3.3, llvm-3.4, llvm-3.5 and master branches.
Released on hackage as versions 3.3.14.2 and 3.4.5.2.
