### ISSUE TITLE
equivalence of IRBuilder::CreateRetVoid()?

### ISSUE THREAD

**Issue by banacorn** [bscarlet/llvm-general#140]
```
ret void
```

How to create a terminator like so?
I've exhausted the documents, but I can't seem to find the right value to constructed this terminator.

There's a equivalence I'm looking for in [the C++ counterpart](http://llvm.org/docs/doxygen/html/classllvm_1_1IRBuilder.html#a5d84e72ef1f1b122131557e4b44f2f0d)

**Comment by bscarlet** [comment]
Use Nothing as the returnOperand field of the Ret constructor of the Terminator type.
