### ISSUE TITLE
llvm-general-pure 3.3.14.3 is broken on base < 4.8

### ISSUE THREAD

**Issue by jarmar** [bscarlet/llvm-general#141]
LLVM.General.Prelude does

    import Prelude hiding (
    ....
    msum
    )

but since Prelude doesn't export msum prior to base-4.8, this fails at compile time with an error message like:

    [ 2 of 23] Compiling LLVM.General.Prelude ( src/LLVM/General/Prelude.hs, dist/build/LLVM/General/Prelude.o )

    src/LLVM/General/Prelude.hs:24:5:
        Module `Prelude' does not export `msum'

**Comment by bscarlet** [comment]
Your logic seems right, but it works for me (& the continuous builds on travis) with ghc-7.6.3 and base-4.6. How exactly are you building when you get the error?

**Comment by jarmar** [comment]
Sorry, maybe the guess I made in the title was too broad. Perhaps some change in base-4.6 makes it work, I'm trying to build with ghc-7.4.2 and base-4.5.1.0:

    $ cabal sandbox init
    $ cabal install --only-dependencies llvm-general-pure-3.3.14.3
    ...
    $ cabal install llvm-general-pure-3.3.14.3
    Resolving dependencies...
    Configuring llvm-general-pure-3.3.14.3...
    Building llvm-general-pure-3.3.14.3...
    Preprocessing library llvm-general-pure-3.3.14.3...
    [ 1 of 23] Compiling LLVM.General.AST.Float ( src/LLVM/General/AST/Float.hs, dist/dist-sandbox-d3655306/build/LLVM/General/AST/Float.o )
    [ 2 of 23] Compiling LLVM.General.Prelude ( src/LLVM/General/Prelude.hs, dist/dist-sandbox-d3655306/build/LLVM/General/Prelude.o )
    
    src/LLVM/General/Prelude.hs:24:5:
        Module `Prelude' does not export `msum'
    Failed to install llvm-general-pure-3.3.14.3
    cabal: Error: some packages failed to install:
    llvm-general-pure-3.3.14.3 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by Et999** [comment]
pre-GHC 7.6 it is an error to hide a non existent function. Now it is no longer an error.

**Comment by jarmar** [comment]
Here's the trac issue in question: https://ghc.haskell.org/trac/ghc/ticket/7167

Apparently the change didn't make it into the changelog. I guess that resolves that the issue is present only on base < 4.6.

**Comment by bscarlet** [comment]
My current aim is only to support the last three versions of GHC (i.e. ghc 7.6, 7.8 & 7.10). I should tighten my dependency on base accordingly, but would accept a PR to add support for 7.4.

**Comment by hvr** [comment]
@bscarlet please add `build-depends: base >= 4.6` in the meantime, as the last couple of Hackage releases  caused compile errors w/ GHC 7.4 (I edit the cabal file there already, so they don't anymore)

**Comment by bscarlet** [comment]
@hvr please elaborate (or offer a PR). You ask that specifically what be updated how? You've edited the cabal file where? (How?). I am not a hackage wizard. Would corrected dependencies in new releases be sufficient, or do old versions' dependencies need to be corrected somehow?

**Comment by hvr** [comment]
> You've edited the cabal file where? (How?).

 - http://hackage.haskell.org/package/llvm-general-pure-3.4.5.4/revisions/
 - http://hackage.haskell.org/package/llvm-general-pure-3.3.14.4/revisions/

> Would corrected dependencies in new releases be sufficient, or do old versions' dependencies need to be corrected somehow?

If you need to retroactively make version constraints tighter then doing this only in new releases isn't enough (as the cabal solver will still be allowed to backtrack to older releases if those allow to satisfy constraints more easily). That's why Hackage was extended to allow to edit metadata to correct for incorrect version bounds in released versions.

However, in my function as [Hackage Trustee](https://github.com/haskell-infra/hackage-trustees), I've taken care of retrofitting tighter `base >= 4.6` lower bounds to the affected releases. So you just need to make sure that future releases have this tighter lower bound as well.

**Comment by bscarlet** [comment]
I've updated the build-depends on the release branches per your recommendations. Thanks.
