### ISSUE TITLE
3.5?

### ISSUE THREAD

**Issue by spacekitteh** [bscarlet/llvm-general#144]
When is LLVM 3.5 gonna be supported?

**Comment by bscarlet** [comment]
Quite soon, hopefully. The awful mess that is the new attribute interface has taken more brain space to design around than I've had available. I've recently gotten the full OK from Google (my employer) to work on it one day a week, so development is picking up again.

**Comment by spacekitteh** [comment]
Sweet. Godspeed!

**Comment by bscarlet** [comment]
The new attribute API is finally disentangled. Proceeding to the other API changes, which will hopefully be smaller.

**Comment by bscarlet** [comment]
It's up on hackage now.
