### ISSUE TITLE
Include llvm-general and llvm-general-pure in stackage

### ISSUE THREAD

**Issue by hjwylde** [bscarlet/llvm-general#157]
Hey, I was wondering if it'd be possible to include `llvm-general` and `llvm-general-pure` in [Stackage](https://www.stackage.org/)?

**Comment by bscarlet** [comment]
I'm not opposed, but neither is it a priority for me.

Stackage's documentation is strangely sparse - a description of the problem it supposedly solves and a cookbook recipe of how to add a package, but no description of what the technical artifact is, how it solves the problem, or what following the recipe would cause to happen. Until it's more mature in that regard the cost of my figuring it out myself is prohibitively high: too much time for me to be able to commit to their maintainers' agreement.

**Comment by tinco** [comment]
Stack is very nice, I use llvm-general in my project which builds using
stack. Right now that works by adding llvm-general to 'extra-deps' (example
here: https://github.com/tinco/nanc). I didn't know there's a big
commitment from maintainers. If I manage to spend more time on my project
and get it in a usable state I could perhaps help out with maintaining
llvm-general. I really do believe Stack is if not the future of Haskell
packaging, what will inspire the future of Haskell packaging.

On Sun, Nov 1, 2015 at 1:41 AM, Benjamin S. Scarlet <
notifications@github.com> wrote:

> I'm not opposed, but neither is it a priority for me.
>
> Stackage's documentation is strangely sparse - a description of the
> problem it supposedly solves and a cookbook recipe of how to add a package,
> but no description of what the technical artifact is, how it solves the
> problem, or what following the recipe would cause to happen. Until it's
> more mature in that regard the cost of my figuring it out myself is
> prohibitively high: too much time for me to be able to commit to their
> maintainers' agreement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bscarlet/llvm-general/issues/157#issuecomment-152783663>
> .
>



-- 
Phusion B.V. | Web Application deployment, scaling, and monitoring solutions

Web: http://www.phusion.nl/
E-mail: info@phusion.nl
Chamber of commerce no: 63501007 (The Netherlands)

**Comment by hjwylde** [comment]
Yeah, at the moment I do have it as an `extra-dep` but having it as part of the snapshots would save having to re-build it multiple times after a `stack clean` and allow for easier caching in Travis.

In the grant scheme of things those are minor benefits though if the maintainers agreement demands a lot from you.
