### ISSUE TITLE
Could not resolve file

### ISSUE THREAD

**Issue by cocreature** [bscarlet/llvm-general#161]
Hey, I’m trying to fix the build error with llvm-3.7 but I get a really weird one on the c++ files
```
Could not resolve file /home/moritz/code/haskell/llvm-general/llvm-general/In file included from src/LLVM/General/Internal/FFI/InstructionC.cpp
```
I don’t really see what’s going on here, so I thought you might have more insight there.

**Comment by bscarlet** [comment]
I don't know what that means either.

**Comment by cocreature** [comment]
Alright, I’ll try to figure it out myself.

**Comment by bscarlet** [comment]
Please feel free to reopen this bug and/or post additional information as you find it. I'm still working on earlier llvm versions, so unless you do it'll be a while before I can even say I think what you're trying to do should work. If nothing else, I am curious where that error message came from, let along what it means.

**Comment by cocreature** [comment]
It looks like it was related to me trying to use stack to build instead of your shake script, using the shake script it works fine.

**Comment by bscarlet** [comment]
Thanks for the update. There's nothing particular special in that shake script - it's just a convenience layer on top of the standard Setup.hs interfaces for llvm-general-pure and llvm-general.
