### ISSUE TITLE
instance IsString Name

### ISSUE THREAD

**Issue by Icelandjack** [bscarlet/llvm-general#170]
Should this be added

``` haskell
instance IsString Name where
  fromString :: String -> Name
  fromString = Name . fromString
```

**Comment by Icelandjack** [comment]
I might suggest a `FromInteger` instance if we had it :)

**Comment by bscarlet** [comment]
While I've certainly been guilty of excessive overloading at times myself, I'm not going to add such an instance.
- I think using IsString for types which are not isomorphic to strings is an abuse of the intent of the typeclass
- Writing lots of literal LLVM code tersely as the AST is not a goal of llvm-general.
