### ISSUE TITLE
An AST instruction was not found in the LLVM instruction defs

### ISSUE THREAD

**Issue by mr-** [bscarlet/llvm-general#98]
I have been trying to compile llvm-general.
It fails at:
[33 of 85] Compiling LLVM.General.Internal.FFI.Builder ( src/LLVM/General/Internal/FFI/Builder.hs, dist/dist-sandbox-3447375f/build/LLVM/General/Internal/FFI/Builder.o )

src/LLVM/General/Internal/FFI/Builder.hs:1:1:
    Exception when trying to run compile-time code:
      An AST instruction was not found in the LLVM instruction defs
      Code: do { ($)
                   liftM (concat)
                   ($)
                     sequence
                     do { let ...;
                          .... } }
Failed to install llvm-general-3.4.2.2
cabal: Error: some packages failed to install:
llvm-general-3.4.2.2 failed during the building phase. The exception was:
ExitFailure 1

I installed llvm-3.4 using apt-get.

uname -a says
Linux mini 3.11.0-17-generic #31-Ubuntu SMP Mon Feb 3 21:52:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abhiranjankumar00** [comment]
@bscarlet resurfaces for this repo (https://github.com/sdiehl/kaleidoscope). Had tried this on llvm-3.3 and llvm-3.4. Default install points to llvm-3.2, tried to _update-alternatives_ few symlinks (llvm-as, llvm-config, llvm-link). Please let me know if I missed something.

Error Code:
```hs
[35 of 91] Compiling LLVM.General.Internal.FFI.Builder ( src/LLVM/General/Internal/FFI/Builder.hs, dist/dist-sandbox-f9a2b2ee/build/LLVM/General/Internal/FFI/Builder.o )

src/LLVM/General/Internal/FFI/Builder.hs:1:1:
    Exception when trying to run compile-time code:
      An AST instruction was not found in the LLVM instruction defs
    Code: do { ($)
                 liftM (concat)
                 ($)
                   sequence
                   do { let ...;
                        .... } }
cabal: Error: some packages failed to install:
llvm-general-3.4.5.3 failed during the building phase. The exception was:
ExitFailure 1

```

```
$ uname -a
Linux Vostro-2520 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bscarlet** [comment]
llvm-general-X.Y.a.b is for llvm-X.Y

It finds llvm based on the version of llvm-config on the path when it's built.

I'd recommend you build llvm from sources, set your path so your newly built llvm-config is the one found, and then build llvm-general. If that works, your original problem is somewhere outside llvm-general.
